version: "3"
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=$USER_ID
        - GID=$GID
    volumes:
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
      - ~/Documents:/host
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
